Sc 74533/trustedform v4 verify language approved
activeprospect/leadconduit-integration-trustedform pull request #117
Opened 2024-07-24 19:02 UTC by GreenAsGrassAP

## Description of the change

updated v4 integration response to append language approved and ensure it is a boolean value

## Type of change
- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change
- [ ] Technical Debt
- [ ] Documentation

## Related tickets

https://app.shortcut.com/active-prospect/story/74533/trustedform-v4-verify-language-approved-is-not-being-appended

## Checklists

### Development and Testing

- [x]  Lint rules pass locally.
- [x]  The code changed/added as part of this pull request has been covered with tests, or this PR does not alter production code.
- [ ]  All tests related to the changed code pass in development, or tests are not applicable.

### Code Review

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached.
- [ ]  At least two engineers have been added as "Reviewers" on the pull request.
- [ ]  Changes have been reviewed by at least two other engineers who did not write the code.
- [ ]  This branch has been rebased off master to be current.

### Tracking 
- [ ]  Issue from Shortcut/Jira has a link to this pull request.
- [ ]  This PR has a link to the issue in Shortcut.

### QA
- [ ]  This branch has been deployed to staging and tested.

2024-07-24 21:39 UTC, cgrayson requested changes
Couple small things; let me know if you have questions!

2024-07-24 21:39 UTC, cgrayson commented on CHANGELOG.md
> +## [2.4.0] - 2024-04-10
You _should_ update the version number (and date) here

2024-07-24 21:39 UTC, cgrayson commented on package.json
> +  "version": "2.4.1",
You _shouldn't_ update the version number here (the "publish to NPM" action will do that)

2024-07-24 21:39 UTC, cgrayson commented on lib/trustedform.js
> +          language_approved: parsed.verify?.result?.language_approved,
Again, like with the `package-lock.json` PR yesterday, this is showing differences that don't exist between this branch and `master`. I don't understand why; I wonder if it's something to do with how you create the branches on GitHub instead of via `git checkout -b`…?

2024-07-24 21:39 UTC, cgrayson commented on test/trustedform_spec.js
> +            ],
This object formatting is weird

2024-07-24 21:39 UTC, cgrayson commented on lib/trustedform.js
> +  { name: 'verify.result.success', type: 'boolean', description: 'A boolean indicating if any of the consent languages found meet the success criteria defined for your account.' },
As with the TF `browser` append data we discussed yesterday, the integration doesn't always need to follow exactly what's returned by the service. I don't think this needs to insert `.result` into this integration's response variables.

2024-07-24 21:39 UTC, cgrayson commented on lib/trustedform.js
> +  { name: 'verify.result.success', type: 'boolean', description: 'A boolean indicating if any of the consent languages found meet the success criteria defined for your account.' },
Also these changed names are wrong: they don't match what's actually set on L183.

2024-07-24 21:39 UTC, cgrayson commented on test/trustedform_spec.js
> +            ],
…which I missed in the previous PR, yet this is another block that shouldn't even show as changed in this PR 🤷  😕

2024-07-25 17:43 UTC, GreenAsGrassAP commented on lib/trustedform.js
> +          language_approved: parsed.verify?.result?.language_approved,
I am still not sure what is causing this but will use the terminal to create any new branches.

2024-07-25 18:39 UTC, cgrayson submitted a review, later dismissed
Looks good; thanks!

2024-07-25 21:07 UTC, cgrayson approved these changes

2024-07-25 21:09 UTC, merged