Sc 74533/trustedform v4 verify language approved is
activeprospect/leadconduit-integration-trustedform pull request #118
Opened 2024-07-29 17:21 UTC by GreenAsGrassAP

## Description of the change

Removed language from response variables per Leandro's suggestion on the shortcut ticket

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change
- [ ] Technical Debt
- [ ] Documentation

## Related tickets

https://app.shortcut.com/active-prospect/story/74533/trustedform-v4-verify-language-approved-is-not-being-appended

## Checklists

### Development and Testing

- [x]  Lint rules pass locally.
- [x]  The code changed/added as part of this pull request has been covered with tests, or this PR does not alter production code.
- [ ]  All tests related to the changed code pass in development, or tests are not applicable.

### Code Review

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached.
- [ ]  At least two engineers have been added as "Reviewers" on the pull request.
- [ ]  Changes have been reviewed by at least two other engineers who did not write the code.
- [ ]  This branch has been rebased off master to be current.

### Tracking 
- [ ]  Issue from Shortcut/Jira has a link to this pull request.
- [ ]  This PR has a link to the issue in Shortcut.

### QA
- [ ]  This branch has been deployed to staging and tested.

2024-07-29 19:50 UTC, josevsalina approved these changes

2024-08-08 14:23 UTC, jgrayson676 reviewed
Are there supposed to be more changes here beyond adding a period to a changelog line?

2024-08-08 14:29 UTC, GreenAsGrassAP commented
I believe it may not be picking up changes as I switched the names on lines 258-260 on file "trustedform.js" back to include "verify." to keep with Leandro's comments.

2024-08-08 21:49 UTC, jgrayson676 requested changes
This change looks fine, but you'll need to update the failing tests accordingly

2024-08-12 14:40 UTC, jgrayson676 commented
Hmm, after this most recent change the PR is back to only adding a period to a changelog entry. What's this PR meant to be changing? It isn't super clear to me from the description.

2024-08-23 14:56 UTC, josevsalina reviewed
is this the only change that you want to merge?

2024-08-23 16:05 UTC, GreenAsGrassAP commented
@josevsalina this should not be necessary. I will update the LC API.

2025-01-08 21:16 UTC, closed without merging