Sc 77184/trustedform v4 verify add 1 1 consent check
activeprospect/leadconduit-integration-trustedform pull request #121
Opened 2024-09-24 16:18 UTC by henriquelakiap

## Description of the change

Adding 1:1 Consent Check Advertiser Name configuration and One To One Filter

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [X] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change
- [ ] Technical Debt
- [ ] Documentation

## Related tickets

[Ticket](https://app.shortcut.com/active-prospect/story/77184/trustedform-v4-verify-add-1-1-consent-check-feature)

## Checklists

### Development and Testing

- [X]  Lint rules pass locally.
- [X]  The code changed/added as part of this pull request has been covered with tests, or this PR does not alter production code.
- [X]  All tests related to the changed code pass in development, or tests are not applicable.

### Code Review

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached.
- [ ]  At least two engineers have been added as "Reviewers" on the pull request.
- [ ]  Changes have been reviewed by at least two other engineers who did not write the code.
- [ ]  This branch has been rebased off master to be current.

### Tracking 
- [ ]  Issue from Shortcut/Jira has a link to this pull request.
- [ ]  This PR has a link to the issue in Shortcut.

### QA
- [ ]  This branch has been deployed to staging and tested.

2024-09-24 16:30 UTC, ericyd requested changes
I'm not seeing Page7 in the PR so it wasn't possible to review everything.

Also, is it possible to add a couple extra tests? I think there's enough logic changes here that it would be worthwhile to add tests, particularly for a high-usage, high-brand-value integration like TF

2024-09-24 16:30 UTC, ericyd commented on lib/ui/public/app/store.js
>      }
I honestly don't know Vuex enough to know if this is 100% necessary, but it would be more idiomatic if `setShouldConfigVerify` were in the `mutations` (because it is not async and just setting a piece of state), and if `getShouldConfigVerify` were in `getters` (because it's a getter)

2024-09-24 16:30 UTC, ericyd commented on lib/ui/public/app/router.js
> +import PageSeven from './config/Page7.vue';
this file is missing from the PR

2024-09-24 16:30 UTC, ericyd commented on lib/ui/public/app/config/Page6.vue
> +      }
this feels wrong - if `shouldConfigVerify` has ever been set, then the user can never use the `confirm` method. That feels confusing. Without seeing what Page7 looks like, I'm not sure what the intended pattern is here, but I think this check should happen elsewhere

2024-09-24 16:30 UTC, ericyd commented on lib/trustedform.js
> +        pickBy({
nitpick, but would be nice if this were indented

2024-09-24 16:39 UTC, jgrayson676 commented on lib/trustedform.js
> +  { name: 'verify.advertiser_name', type: 'string', required: false, description: 'The name of the legal entity for an advertiser that will be used to determine if they were given consent in a one to
Maybe I'm missing something or misunderstood the ticket, but I don't see where this value is included in the request. If this will add an additional field into the request then we'll also want those tests updated appropriately.

2024-09-24 19:17 UTC, ericyd commented on lib/ui/public/app/store.js
> +        };
I'm a little confused by this structure too -- is it intentional that the `else` clause has a nested `rules` key?

2024-09-24 19:17 UTC, ericyd commented on lib/ui/public/app/store.js
> +          isArray(rules) ? set(filterConfig, 'rules', rules) : assign(filterConfig, rules);
I don't think we need this array check. `rules` is initialized to an array about 8 lines above this.

2024-09-25 14:57 UTC, jgrayson676 commented on lib/trustedform.js
> +  { name: 'one_to_one', type: 'boolean', description: 'A boolean indicating if the cert structure satisfied the requirements for 1:1 consent., and is available to use in filters' },
IMO having 'is available to use in filters' in the description is redundant and potentially somewhat misleading, but if we want to keep it then the period after 'consent' should be removed

2024-09-25 19:24 UTC, ericyd commented on lib/trustedform.js
> +          : undefined;
should this include one_to_one?

2024-09-25 19:24 UTC, ericyd commented on lib/ui/public/app/config/Page4.vue
> +      return true // LAKI this.products.retain.enabled || this.products.insights.enabled || this.products.verify.enabled;
?

2024-09-25 19:24 UTC, ericyd commented on test/trustedform_spec.js
> +        one_to_one: true,
shouldn't one_to_one be nested inside the `verify` object below? I guess the product reqs are slightly ambiguous, but it seems weird that this feature is specific to `verify` but not nested under the `verify` label

2024-09-25 19:24 UTC, ericyd commented on lib/ui/public/app/config/Page7.vue
> +/** override this style https://github.com/activeprospect/leadconduit-client/blob/a005d3ac5627aa39d12c64756561ef400b512bf3/public/css/core/forms.styl#L252-L254 */
these comments aren't relevant anymore

2024-09-25 19:24 UTC, ericyd commented on lib/ui/public/app/store.js
> +      verify: { enabled: true, selected: false }
?

2024-09-25 19:24 UTC, ericyd commented on lib/ui/public/app/store.js
> +          set(filterConfig, 'rules', rules);
why are we using `set` here instead of adding it to the object definition above? I would think we should either have a block like this

```
const filterConfig = {}
set(filterConfig, 'reason', '{{trustedform.reason}}')
set(filterConfig, 'outcome', 'failure')
...more set() calls
```

or like this

```
const filterConfig = {
  reason: '{{trustedform.reason}}',
  outcome: 'failure',
  description: 'Filter leads that fail on Trustedform Verify check',
  rules
};
```

2024-09-26 12:52 UTC, henriquelakiap commented on lib/trustedform.js
> +          : undefined;
one_to_one will not be added in verify property.  The ticket scope says it should be in trustedform.one_to_one

2024-09-26 12:55 UTC, henriquelakiap commented on test/trustedform_spec.js
> +        one_to_one: true,
Yeah. the first implementation was under trustedform.verify.one_to_one, but then the field name didn't match what was defined. So I moved it to trustedform.one_to_one

2024-09-26 16:22 UTC, jgrayson676 approved these changes

2024-09-26 17:12 UTC, ericyd approved these changes
Nice! 🎉

2024-09-26 17:13 UTC, merged